spin: add a sleep(n) capability (default 2 seconds) between invocations, and also a clear-screen between invocations

diff --git a/bin/spin b/bin/spin
--- a/bin/spin
+++ b/bin/spin
@@ -1,23 +1,33 @@
 #!/bin/bash
 
+myname="${0##*/}"
+
+function usage {
+    exec >&2
+    [[ $# -gt 0 ]] && echo "ERROR: $*"
+
+    echo "usage: $myname [-c] [-s#] somecmd someargs"
+    exit 1
+}
+
+
 # must be in a Rails environment - since that's where I'm using this...
-[[ -f Gemfile ]] || {
-    echo >&2 ${0##*/}: must be in a Rails environment, same directory as the Gemfile
-    exit 1
-}
+[[ -f Gemfile ]] || usage "must be in a Rails environment, same directory as the Gemfile"
 
+sleepy=2
 scroll=:
-if [[ "X$1" = X-c ]]; then
-    scroll=scroll
-    shift
-fi
+while getopts :cs: ch; do
+    case "$ch" in
+      c) scroll=scroll ;;
+      s) sleepy="$OPTARG" ;;
+      *) usage "invalid option: $ch";;
+    esac
+done
+shift $((OPTIND-1))
 
-[[ $# -gt 0 ]] || {
-    echo >&2 usage: ${0##*/} somecmd someargs
-    exit 1
-}
+[[ $# -gt 0 ]] || usage
 
 trap : 2            # INT kills the program but keeps the spin
 trap 'exit 1' 3     # QUIT kills the program and stop spinning
-while ( trap 2 3; exec "$@" ); do $scroll; done
+while ( trap 2 3; sleep $sleepy; exec "$@" ); do $scroll; done
 
