git jones: make it allow more than one branch to be present

diff --git a/bin.f/git b/bin.f/git
--- a/bin.f/git
+++ b/bin.f/git
@@ -170,40 +170,41 @@ git() {
         fi
         ;;
 
-      jones)      # as in, keeping up with... merge stuff from main branch that this branch hangs off
+      jones)      # as in, keeping up with the... merge stuff from main branch that this branch hangs off
         # NOTE: only works for Tickit apps - no convention has been established for other worlds
         call=
 
-        # Detect all branches in this project. Wait for it, you'll find out why...
+        # Detect all branches in this project - prove there is a single rel- and we are on a tod- or ts-
         # The sed is making the output of git branch a bit more regular so it's easy to parse with dumb shell.
         command git branch | sed 's/^ /-/; s/^\(.\) \(.*\)/\2 \1/' | sort | {
-            typeset -a branches
-            this=
+            this= main=
 
-            # Gather list of branches and their statii.
+            # Examine list of branches and their state - look for current and a single rel- branch.
             while read name state; do
                 [[ "$state" == '*' ]] && this="$name"
-                branches+=("$name")
+
+                if [[ "$name" == rel-+([0-9])+(.+([0-9]))*([a-z]) ]]; then
+                    if [[ -n "$main" ]]; then
+                        echo >&2 "There is more than one rel- branch. Cannot keep up with two Jones' families."
+                        main=DUD
+                        break
+                    fi
+
+                    main="$name"
+                fi
             done
 
-            # Assuming there's 2 branches...
-            main="${branches[0]}"
-            dev="${branches[1]}"
-
-            # Merge the branch if it's alone in this project with a release branch.
-            if [[ "${#branches[@]}" -eq 2 && "$this" == @(tos|ts)-+([0-9])*([a-z]) ]] && [[ "$main" == rel-+([0-9])+(.+([0-9]))*([a-z]) && "$dev" == @(tos|ts)-+([0-9])*([a-z]) ]]; then
-                # Proven:
-                #  This directory only has 2 local branches: a release (branch it's following) and a development branch.
-                #  Current branch is the development branch.
-
+            # Merge the branch if it's current in this project, next to a release branch.
+            if [[ "$main" == rel-+([0-9])+(.+([0-9]))*([a-z]) && "$this" == @(tos|ts)-+([0-9])*([a-z]) ]]; then
+                # Proven: This directory has a release branch it's following, and we are on a development branch.
                 if git status --porcelain | sed 's/^ /./; s/^\(.\)\(.\) \(.*\)$/\1 \2 \3/; /^[?!]/d' | grep -q .; then
-                    echo >&2 "Significant uncommitted work exists - cannot merge release $main to $dev"
+                    echo >&2 "Significant uncommitted work exists - cannot merge release $main to $this"
                 else
                     echo "Merging from origin/$main"
                     git merge -X patience "origin/$main"
                 fi
             else
-                echo >&2 "There must only be a rel- and a @(tos|ts)- branch, and you must currently be on the @(tos|ts)- branch"
+                echo >&2 "There must be a single rel- and some @(tos|ts)- branches, and you must currently be on a @(tos|ts)- branch"
             fi
         }
         ;;
