git wrapper: support M V or C options to pre-cd into special directories

diff --git a/bin.f/git b/bin.f/git
--- a/bin.f/git
+++ b/bin.f/git
@@ -118,7 +118,7 @@ app() {
         v) vflag=1 ;;   # verbalise
         N) Nflag=1 ;;   # go Native - make the current branch match the project
 
-        *) echo >&2 "usage: app [-l] [-n] [-v] [-N] [project]"
+        *) echo >&2 "usage: app [-l] [-n] [-v] [-N] [M|V|C] [project]"
            return 1 ;;
       esac
     done
@@ -173,6 +173,22 @@ app() {
         return 0
     fi
 
+    target=
+    if [[ "$1" == [MVC] ]]; then
+        if [[ -n "$nflag" ]]; then
+            echo >&2 "Cannot use -n with M, V, or C"
+            return 1
+        fi
+
+        case "$1" in
+          M) target=/app/models ;;
+          V) target=/app/views ;;
+          C) target=/app/controllers ;;
+        esac
+
+        shift
+    fi
+
     if [[ $# -gt 0 ]]; then
         local vers="$1"
         case "$vers" in
@@ -185,8 +201,9 @@ app() {
         export APP=~/tickit/"$vers"
     fi
 
-    [[ -z "$nflag" ]] && cd "$APP" && know_branch >/dev/null 2>/dev/null
-    [[ -n "$vflag" ]] && echo "APP = $APP"
+    [[ -n "$target" ]] && clear
+    [[ -z "$nflag" ]]  && cd "$APP$target" && know_branch >/dev/null 2>/dev/null
+    [[ -n "$vflag" ]]  && echo "APP = $APP"
 
     return 0
 }  # app
